language: rust

cache: cargo

dist: trusty

os:
  - linux
  - osx

rust:
  - stable

branches:
  only:
    - master

before_script:
  - rustup component add rustfmt-preview

script:
  - cargo fmt --all -- --write-mode=diff
  - cargo build --verbose
  - cargo test --verbose
